library:
  source-dirs: src
  default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyDataDecls
  - FlexibleContexts
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternGuards
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
tests:
  typechecker-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typechecker
    default-extensions:
    - ConstraintKinds
    - DataKinds
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DerivingStrategies
    - EmptyDataDecls
    - FlexibleContexts
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - OverloadedStrings
    - PatternGuards
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TupleSections
copyright: 2020 Kamil Listopad
ghc-options:
- -Weverything
- -Wno-unsafe
- -Wno-safe
- -Wno-missing-import-lists
- -Wno-missing-export-lists
- -Wno-missing-local-signatures
dependencies:
- containers
- data-fix
- base >= 4.7 && < 5
- protolude
- microlens-platform
- prettyprinter
- dlist
name: typechecker
version: 0.1.0.0
extra-source-files:
- README.md
author: Kamil Listopad
github: kamirus/typechecker
license: MIT
executables:
  typechecker-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typechecker
